module.exports = {
	arrowParens: "always",
	bracketSpacing: true,
	endOfLine: "lf",
	htmlWhitespaceSensitivity: "css",
	insertPragma: false,
	singleAttributePerLine: false,
	bracketSameLine: false,
	jsxBracketSameLine: false,
	jsxSingleQuote: false,
	proseWrap: "preserve",
	quoteProps: "as-needed",
	requirePragma: false,
	semi: true,
	singleQuote: false,
	tabWidth: 5,
	trailingComma: "es5",
	useTabs: true,
	vueIndentScriptAndStyle: false,
	printWidth: 133, // increase this value from 80 (default) to a higher value like 120
};
